CREATE DATABASE IF NOT EXISTS logbook;

USE logbook;

CREATE TABLE log (
    name VARCHAR(40) PRIMARY KEY,
	visiting VARCHAR(40) NOT NULL,
	timein TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	timeout TIMESTAMP NULL
);
